### ISSUE TITLE
I'm trying to wrap my head around django-mutant...

### ISSUE THREAD

**Issue by sewpafly** [afaikafk/mutant-sample-app#1]
I'm running the mutant-sample-app and i have successfully created models and fields for those models, but I was wondering what's next? (By the way thanks for this app, it's a great tool to play with django mutant)

Specifically:
- How do you go about pairing dynamic models and fields into your own apps? (How can I play with the models using the django shell?)
- How do you add new dynamic models into the django admin to add/modify data?

**Comment by sewpafly** [comment]
From the shell here's how you add data:

```
from mutant import models

my_model = models.ModelDefinition.objects.filter(name='mymodel')[0].model_class()
instance = my_model.create()
```

Still haven't figured out how to add that model to django admin...

**Comment by afaikafk** [comment]
Hi!
I've asked a similar question from Simon, when I began experimenting with mutant. These models are not automatically registered, not even in the app cache, Simon showed a solution for that here:

https://github.com/charettes/django-mutant/issues/4

you could as well register the model using the same technique to show up in the admin panel.

**Comment by sewpafly** [comment]
Would you know where to put that code? I tried putting it into `admin.py` and that doesn't appear to work.

**Comment by afaikafk** [comment]
Moved the sample snippet from the previous comment to a new, as it was submitted about the same time as your question.

```
"""belongs into admin.py"""
from django.contrib import admin

from mutant.models import ModelDefinition


for md in ModelDefinition.objects.all():
    model_cls = md.model_class()
    admin.site.register(model_cls.model_class().__class__)
```

Did it solve your problem?

**Comment by sewpafly** [comment]
Exactly what i was looking for, thanks!
